name: Build and Push to GCR

on:
  push:
    branches:
      - main

env:
  NAME: eso-vm-server
jobs:
  publish-artifacts:
    uses: external-secrets-inc/actions/.github/workflows/publish.yml@main
    permissions:
      id-token: write
      contents: read
    strategy:
      matrix:
        include:
        - dockerfile: "Dockerfile"
          build-args: "CGO_ENABLED=1"
          build-arch: "amd64 arm64"
          build-platform: "linux/amd64,linux/arm64"
          tag-suffix: "" # distroless
    with:
      dockerfile: ${{ matrix.dockerfile }}
      tag-suffix: ${{ matrix.tag-suffix }}
      image-name: us-central1-docker.pkg.dev/external-secrets-inc-registry/external/eso-vm-server
      build-platform: ${{ matrix.build-platform }}
      build-args: ${{ matrix.build-args }}
      build-arch: ${{ matrix.build-arch }}
      name: "eso-vm-server"
      ref: ${{ github.ref }}
    secrets:
      ESI_BOT_PRIVATE_KEY: ${{ secrets.ESI_BOT_PRIVATE_KEY }}
